"""
Build dossier cards for the 4 anchor genes locked at step 3.

Anchors:
    PMM0958     — driving example A (rich content, DUF1830, 3 clusters, 1 vesicle DM)
    PMM1898     — driving example B (F1 floor: AQ=0, no ontology, singleton curated cyanorak group)
    PMM0246     — positive control (ntcA, AQ=3, 16 ontology terms, K-means N-stress cluster 2)
    TX50_RS09500 — F3 floor (RefSeq-only, no clusters, no homologs, no ontology)

Outputs (default ../data/):
    dossiers.json            Structured dossier cards (one entry per anchor; aggregated)
    cards/<locus_tag>.md     One markdown card per gene
    index.md                 1-line summary per gene with link to its card
    group_probe_cache.json   Cached signal probe envelopes (reusable at step 5)
"""

import argparse
import json
import sys
from pathlib import Path

# Make dossier.py importable as a sibling
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from dossier import GroupProbeCache, build_dossier, render_card_markdown

LOCKED_EXPERIMENT_ID = (
    "10.1101/2025.11.24.690089_growth_state_pro99lown_nutrient_starvation_med4_rnaseq_axenic"
)
ORGANISM = "MED4"

ANCHORS = [
    ("PMM0958", "driver A — rich"),
    ("PMM1898", "driver B — F1 floor (singleton ortholog group)"),
    ("PMM0246", "positive control — ntcA"),
    ("TX50_RS09500", "F3 floor — RefSeq-only, no cluster/homolog/ontology"),
]


def _index_row(card: dict, role: str) -> str:
    """Build a 1-line summary row for the index."""
    ident = card.get("identity") or {}
    de = card.get("de_evidence") or {}
    n_clusters = len(card.get("clusters") or [])
    n_groups = len(card.get("ortholog_groups") or [])
    n_ontology = len(card.get("ontology") or [])
    n_dms = len(card.get("derived_metrics") or [])
    log2fc = de.get("log2fc")
    log2fc_str = f"{log2fc:.2f}" if isinstance(log2fc, (int, float)) else "—"
    aq = ident.get("annotation_quality")
    name = ident.get("gene_name") or ""
    product = (ident.get("product") or "")[:60]
    locus_tag = card["locus_tag"]
    return (
        f"- [`{locus_tag}`](cards/{locus_tag}.md)"
        f"{' (' + name + ')' if name else ''}"
        f" — log2fc {log2fc_str}, AQ {aq}, {product}"
        f" · clusters={n_clusters}, ortholog_groups={n_groups}, ontology={n_ontology}, DMs={n_dms}"
        f" · _{role}_"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path(__file__).resolve().parent.parent / "data")
    args = parser.parse_args()
    args.data_dir.mkdir(parents=True, exist_ok=True)
    cards_dir = args.data_dir / "cards"
    cards_dir.mkdir(parents=True, exist_ok=True)

    cache_path = args.data_dir / "group_probe_cache.json"
    cache = GroupProbeCache(cache_path=cache_path)

    cards = []
    index_rows = []
    for locus_tag, role in ANCHORS:
        print(f"\n=== building dossier for {locus_tag} ({role}) ===", flush=True)
        card = build_dossier(
            locus_tag=locus_tag,
            locked_experiment_id=LOCKED_EXPERIMENT_ID,
            organism=ORGANISM,
            group_cache=cache,
        )
        card["__role"] = role
        cards.append(card)

        md = render_card_markdown(card)
        # Append a small footer with the role
        md_with_role = md + f"\n_role: {role}_\n"
        card_path = cards_dir / f"{locus_tag}.md"
        card_path.write_text(md_with_role)
        print(f"  wrote {card_path}", flush=True)

        index_rows.append(_index_row(card, role))

    out_json = args.data_dir / "dossiers.json"
    out_json.write_text(json.dumps(cards, indent=2, default=str))
    print(f"\nwrote {out_json} ({len(cards)} cards aggregated)", flush=True)

    index_md = args.data_dir / "index.md"
    index_md.write_text(
        "# Dossier index — anchor genes (step 4)\n\n"
        f"Generated by `01_build_dossier_anchors.py`. Each entry links to a per-gene card under `cards/`.\n\n"
        f"Locked experiment: `{LOCKED_EXPERIMENT_ID}`\n\n"
        + "\n".join(index_rows)
        + "\n"
    )
    print(f"wrote {index_md}", flush=True)

    cache.save()
    print(f"wrote {cache_path} ({len(cache._cache)} cached probes)", flush=True)


if __name__ == "__main__":
    main()
